import type { Metadata } from "next";
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/700.css';
import '@fontsource/poppins/400.css';
import '@fontsource/poppins/600.css'; 
import "./globals.css";
import NavbarApp from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavbarApp />
        {children}
        <Footer />
      </body>
    </html>
  );
}
